"""Port of SimCardFileMapping / MFSimCardFileMapping / USIMCardFileMapping / ISIMCardFileMapping."""

from __future__ import annotations


class SimCardFileMapping:
    def _get_files_details(self) -> dict:
        return {}

    def _format_path(self, path: str) -> str:
        parts = [path[i:i + 4] for i in range(0, len(path), 4)]
        return "/".join(parts)

    def _get_filename_and_human(self, formatted_path: str):
        return self._get_files_details().get(formatted_path.lower(), ("N/A", "N/A"))

    def get_mapped_name_and_description(self, input_file_paths: dict, aid: str | None = None) -> list:
        results = []

        for path in sorted(input_file_paths.keys()):
            formatted_path = self._format_path(path)
            name, description = self._get_filename_and_human(formatted_path)

            file = input_file_paths[path]
            file.set_file_path(formatted_path)
            file.set_file_name(name)
            file.set_file_description(description)

            results.append(file)

        if aid is not None:
            for file in results:
                file.set_file_path(file.get_file_path().replace("7FFF", aid))

        return results


class MFSimCardFileMapping(SimCardFileMapping):
    def _get_files_details(self) -> dict:
        return {
            "3f00": ("MF", "Root Directory"),
            "3f00/2f00": ("EFdir", "Application directory"),
            "3f00/2f05": ("PL", "Preferred Languages"),
            "3f00/2f06": ("MF/arr", "Access Rule Reference"),
            "3f00/2f53": ("Axalto (U)Simera", "file that is used by the STK framework in case of an SMS PP Unformatted UPD"),
            "3f00/2fe2": ("ICCID", "ICC Identification"),
            "3f00/2fe5": ("PIN", "Keys for CHV1; CHV2; PUK1; PUK2; and ADMx for GSM"),
            "3f00/2fe6": ("Key", "Ki for GSM authentication and OTA’s Authentication Keys Kid"),
            "3f00/5f11": ("Gemplus GemXpresso", "file that is used by the STK framework in case of an SMS PP Unformatted UPD"),

            "3f00/7f10": ("DFtelecom", "Telecom Directory"),
            "3f00/7f10/6f06": ("DFtelecom/arr", "Access Rule Reference"),
            "3f00/7f10/6f3a": ("ADN", "Abbrev numbers"),
            "3f00/7f10/6f3b": ("FDN", "Fixed numbers"),
            "3f00/7f10/6f3c": ("SMS", "SMS"),
            "3f00/7f10/6f3d": ("CCP", "Capability conf"),
            "3f00/7f10/6f40": ("MSISDN", "MSISDN"),
            "3f00/7f10/6f42": ("SMSP", "SMS parameters"),
            "3f00/7f10/6f43": ("SMSS", "SMS status"),
            "3f00/7f10/6f44": ("LND", "Last number dialled"),
            "3f00/7f10/6f47": ("SMSR", "SMS Status reports"),
            "3f00/7f10/6f49": ("SDN", "Service Dialling Nrs"),
            "3f00/7f10/6f4a": ("EXT1", "Extension 1"),
            "3f00/7f10/6f4b": ("EXT2", "Extension 2"),
            "3f00/7f10/6f4c": ("EXT3", "Extension 3"),
            "3f00/7f10/6f4d": ("BDN", "Barred Numbers"),
            "3f00/7f10/6f4e": ("EXT4", "Extension 4"),
            "3f00/7f10/6f4f": ("ECCP", "Extended Capability Configuration Parameter"),
            "3f00/7f10/6f53": ("RMA", "Remote Management Actions"),
            "3f00/7f10/6f54": ("SUME", "SetUpMenu Elements"),
            "3f00/7f10/6f58": ("CMI", "Comparison Method Information"),
            "3f00/7f10/6fe0": ("ICE_DN", "In Case of Emergency – Dialling Number)"),
            "3f00/7f10/6fe1": ("ICE_FF", "In Case of Emergency – Free Format)"),
            "3f00/7f10/6fe5": ("PSISMSC", "Public Service Identity of the SM-SC"),
            "3f00/7f10/5f3a": ("DFphonebook", "Phone book Directory"),
            "3f00/7f10/5f3a/4f22": ("PSC", "PBook Sync counter"),
            "3f00/7f10/5f3a/4f23": ("CC", "PBook Change counter"),
            "3f00/7f10/5f3a/4f24": ("PUID", "PBook previous UID"),
            "3f00/7f10/5f3a/4f30": ("PBR", "PBook reference"),
            "3f00/7f10/5f3a/0000": ("PBccp1", "PBook Capability"),
            "3f00/7f10/5f3a/4f09": ("PBc", "PBook Control"),
            "3f00/7f10/5f3a/4f11": ("PBanr", "PBook addition nr"),
            "3f00/7f10/5f3a/4f19": ("PBsne", "PBook Second Name"),
            "3f00/7f10/5f3a/4f21": ("PBuid", "PBook Unique ID"),
            "3f00/7f10/5f3a/4f26": ("PBgrp", "PBook groups"),
            "3f00/7f10/5f3a/4f3a": ("PBadn", "PBook Abbrev numbers"),
            "3f00/7f10/5f3a/4f4a": ("PBext1", "PBook extension 1"),
            "3f00/7f10/5f3a/4f4b": ("PBass", "PBook additional nrs"),
            "3f00/7f10/5f3a/4f4c": ("PBgas", "PBook group desc"),
            "3f00/7f10/5f3a/4f50": ("PBemail", "PBook email address"),
            "3f00/7f10/5f50/4f20": ("IMG", "Image"),

            "3f00/7f20": ("DFgsm", "GSM Directory"),
            "3f00/7f20/5f30": ("DFiridium", ""),
            "3f00/7f20/5f31": ("DFglobst", ""),
            "3f00/7f20/5f32": ("DFico", ""),
            "3f00/7f20/5f33": ("DFaces", ""),
            "3f00/7f20/5f3c": ("DFmexe", "Mobile Execution Environment Directory"),
            "3f00/7f20/5f3c/4f40": ("MExE-ST", "Mobile Execution Environment Service Table"),
            "3f00/7f20/5f3c/4f41": ("ORPK", "Operator root public key"),
            "3f00/7f20/5f3c/4f42": ("ARPK", "Administrator root public key"),
            "3f00/7f20/5f3c/4f43": ("TPRPK", "Third Party root public key"),
            "3f00/7f20/5f40": ("DFeia/tia-553", "EIT/TIA-553 Analog Cellular Directory"),
            "3f00/7f20/5f60": ("DFcts", "Cordless Telephony System Directory"),
            "3f00/7f20/5f70": ("DFsolsa", "Support of Localised Service Area Directory"),
            "3f00/7f20/5f70/4f30": ("SAI", "SoLSA Access Indicator"),
            "3f00/7f20/5f70/4f31": ("SLL", "SoLSA LSA List"),
            "3f00/7f20/6f05": ("LP", "Language Preference"),
            "3f00/7f20/6f07": ("IMSI", "IMSI"),
            "3f00/7f20/6f09": ("KeyPS", "Keys for Packet domain"),
            "3f00/7f20/6f20": ("Kc", "Ciphering key Kc"),
            "3f00/7f20/6f2c": ("DCK", "De-personalise Key"),
            "3f00/7f20/6f30": ("PLMNsel", "PLMN selector"),
            "3f00/7f20/6f31": ("HPPLMN", "HPLMN search period"),
            "3f00/7f20/6f32": ("CNL", "Co-operative Networks"),
            "3f00/7f20/6f37": ("ACMmax", "ACM maximum value"),
            "3f00/7f20/6f38": ("SST", "SIM service table"),
            "3f00/7f20/6f39": ("ACM", "Call meter"),
            "3f00/7f20/6f3e": ("GID1", "Group Id Level 1"),
            "3f00/7f20/6f3f": ("GID2", "Group Id Level 2"),
            "3f00/7f20/6f41": ("PUCT", "Price per unit"),
            "3f00/7f20/6f45": ("CBMI", "Bcast msg id"),
            "3f00/7f20/6f46": ("SPN", "Network Name"),
            "3f00/7f20/6f48": ("CMMID", "Cell BCast for Data"),
            "3f00/7f20/6f50": ("CBMIR", "Cell BCast msg ID"),
            "3f00/7f20/6f51": ("NIA", "Network Ind Alerting"),
            "3f00/7f20/6f52": ("KcGPRS", "GPRS Ciphering Key"),
            "3f00/7f20/6f53": ("LOCIGPRS", "GPRS location info"),
            "3f00/7f20/6f54": ("SUME", "SetUpMenu Elements"),
            "3f00/7f20/6f60": ("PLMNwAcT", "User PLMN Selector"),
            "3f00/7f20/6f61": ("OPLMNwAcT", "OPerator PLMN Select"),
            "3f00/7f20/6f62": ("HPLMNwAcT", "HPLMN Selector"),
            "3f00/7f20/6f63": ("CPBCCH", "CPBCCH Information"),
            "3f00/7f20/6f64": ("InvScan", "Investingation Scan"),
            "3f00/7f20/6f74": ("BCCH", "Bcast control chans"),
            "3f00/7f20/6f78": ("ACC", "Access control class"),
            "3f00/7f20/6f7b": ("FPLMN", "Forbidden PLMNs"),
            "3f00/7f20/6f7e": ("LOCI", "Location information"),
            "3f00/7f20/6fad": ("AD", "Administrative data"),
            "3f00/7f20/6fae": ("Phase", "Phase identification"),
            "3f00/7f20/6fb1": ("VGCS", "Voice call group srv"),
            "3f00/7f20/6fb2": ("VGCSS", "Voice group call stat"),
            "3f00/7f20/6fb3": ("VBS", "Voice broadcast srv"),
            "3f00/7f20/6fb4": ("VBSS", "Voice broadcast stat"),
            "3f00/7f20/6fb5": ("eMLPP", "Enhan Mult Lvl Prio"),
            "3f00/7f20/6fb6": ("AAeM", "Auto Answer for eMLPP"),
            "3f00/7f20/6fb7": ("ECC", "Emergency Call Codes"),
            "3f00/7f20/6fc5": ("PNN", "PLMN Network Name"),
            "3f00/7f20/6fc6": ("OPL", "Operator PLMN list"),
            "3f00/7f20/6fc7": ("MBDN", "Mailbox Dialling Nrs"),
            "3f00/7f20/6fc8": ("EXT6", "Extension6"),
            "3f00/7f20/6fc9": ("MBI", "Mailbox Identifier"),
            "3f00/7f20/6fca": ("MWIS", "Message Waiting Stat"),
            "3f00/7f20/6fcb": ("CFIS", "Call Fwd Ind Status"),
            "3f00/7f20/6fcc": ("EXT7", "Extension7"),
            "3f00/7f20/6fcd": ("SPDI", "Service Prov Display"),
            "3f00/7f20/6fce": ("MMSN", "MMS Notification"),
            "3f00/7f20/6fcf": ("EXT8", "Extension8"),
            "3f00/7f20/6fd0": ("MMSICP", "MMS Issuer Params"),
            "3f00/7f20/6fd1": ("MMSUP", "MMS User Preferences"),
            "3f00/7f20/6fd2": ("MMSUCP", "MMS User Params"),
            "3f00/7f20/6f06": ("USIMarr", "Access Rule Reference"),
            "3f00/7f20/6f08": ("USIMkeys", "Ciphering and keys"),
            "3f00/7f20/6f3b": ("USIMfdn", "Fixed numbers"),
            "3f00/7f20/6f3c": ("USIMsms", "SMS"),
            "3f00/7f20/6f40": ("USIMmsisdn", "MSISDN"),
            "3f00/7f20/6f42": ("USIMsmsp", "SMS parameters"),
            "3f00/7f20/6f43": ("USIMsmss", "SMS status"),
            "3f00/7f20/6f47": ("USIMsmsr", "SMS Status reports"),
            "3f00/7f20/6f49": ("USIMsdn", "Service Dialling Nrs"),
            "3f00/7f20/6f4a": ("USIMext1", "Extension 1"),
            "3f00/7f20/6f4b": ("USIMext2", "Extension 2"),
            "3f00/7f20/6f4c": ("USIMext3", "Extension 3"),
            "3f00/7f20/6f4d": ("USIMbdn", "Barred Numbers"),
            "3f00/7f20/6f4e": ("USIMext5", "Extension 5"),
            "3f00/7f20/6f4f": ("USIMccp2", "Capability Config 2"),
            "3f00/7f20/6f55": ("USIMext4", "Extension 4"),
            "3f00/7f20/6f56": ("USIMest", "Enabled Services"),
            "3f00/7f20/6f57": ("USIMacl", "Access Control List"),
            "3f00/7f20/6f58": ("USIMcmi", "Comparision Method"),
            "3f00/7f20/6f5b": ("USIMstarthfn", "Init for Hyperframe"),
            "3f00/7f20/6f5c": ("USIMthreshold", "Max value for START"),
            "3f00/7f20/6f73": ("USIMpsloci", "Packet switched locn"),
            "3f00/7f20/6f80": ("USIMici", "Incoming Calls"),
            "3f00/7f20/6f81": ("USIMoci", "Outgoing Calls"),
            "3f00/7f20/6f82": ("USIMict", "Incoming Call Timer"),
            "3f00/7f20/6f83": ("USIMoct", "Outgoing Call Timer"),
            "3f00/7f20/6fc3": ("USIMhiddenkey", "Key for hidden pbook"),
            "3f00/7f20/6fc4": ("USIMnetpar", "Network parameters"),
            "3f00/7f20/6fd3": ("USIMnia", "Network Ind Alerting"),
            "3f00/7f20/6fd4": ("USIMvgcsca", "Voice grp cipher alg"),
            "3f00/7f20/6fd5": ("USIMvbsca", "Voice brd cipher alg"),
            "3f00/7f20/6fd6": ("USIMgbabp", "GBA Bootstrap"),
            "3f00/7f20/6fd7": ("USIMmsk", "MBMS Service Keys"),
            "3f00/7f20/6fd8": ("USIMmuk", "MBMS User Key"),
            "3f00/7f20/6fd9": ("USIMehplmn", "Evuiv HPLMN"),
            "3f00/7f20/6fda": ("USIMgbanl", "GBA NAF List"),
            "3f00/7f20/5f3b": ("DFmultimedia", "Multi media Directory"),

            "3f00/7f21": ("DF DCS1800", "DCS1800 Directory"),
            "3f00/7f21/6f05": ("LP", "Language Preference"),
            "3f00/7f21/6f07": ("IMSI", "IMSI"),
            "3f00/7f21/6f09": ("KeyPS", "Keys for Packet domain"),
            "3f00/7f21/6f20": ("Kc", "Ciphering key Kc"),
            "3f00/7f21/6f2c": ("DCK", "De-personalise Key"),
            "3f00/7f21/6f30": ("PLMNsel", "PLMN selector"),
            "3f00/7f21/6f31": ("HPPLMN", "HPLMN search period"),
            "3f00/7f21/6f32": ("CNL", "Co-operative Networks"),
            "3f00/7f21/6f37": ("ACMmax", "ACM maximum value"),
            "3f00/7f21/6f38": ("SST", "SIM service table"),
            "3f00/7f21/6f39": ("ACM", "Call meter"),
            "3f00/7f21/6f3e": ("GID1", "Group Id Level 1"),
            "3f00/7f21/6f3f": ("GID2", "Group Id Level 2"),
            "3f00/7f21/6f41": ("PUCT", "Price per unit"),
            "3f00/7f21/6f45": ("CBMI", "Bcast msg id"),
            "3f00/7f21/6f46": ("SPN", "Network Name"),
            "3f00/7f21/6f48": ("CMMID", "Cell BCast for Data"),
            "3f00/7f21/6f50": ("CBMIR", "Cell BCast msg ID"),
            "3f00/7f21/6f51": ("NIA", "Network Ind Alerting"),
            "3f00/7f21/6f52": ("KcGPRS", "GPRS Ciphering Key"),
            "3f00/7f21/6f53": ("LOCIGPRS", "GPRS location info"),
            "3f00/7f21/6f54": ("SUME", "SetUpMenu Elements"),
            "3f00/7f21/6f60": ("PLMNwAcT", "User PLMN Selector"),
            "3f00/7f21/6f61": ("OPLMNwAcT", "OPerator PLMN Select"),
            "3f00/7f21/6f62": ("HPLMNwAcT", "HPLMN Selector"),
            "3f00/7f21/6f63": ("CPBCCH", "CPBCCH Information"),
            "3f00/7f21/6f64": ("InvScan", "Investingation Scan"),
            "3f00/7f21/6f74": ("BCCH", "Bcast control chans"),
            "3f00/7f21/6f78": ("ACC", "Access control class"),
            "3f00/7f21/6f7b": ("FPLMN", "Forbidden PLMNs"),
            "3f00/7f21/6f7e": ("LOCI", "Location information"),
            "3f00/7f21/6fad": ("AD", "Administrative data"),
            "3f00/7f21/6fae": ("Phase", "Phase identification"),
            "3f00/7f21/6fb1": ("VGCS", "Voice call group srv"),
            "3f00/7f21/6fb2": ("VGCSS", "Voice group call stat"),
            "3f00/7f21/6fb3": ("VBS", "Voice broadcast srv"),
            "3f00/7f21/6fb4": ("VBSS", "Voice broadcast stat"),
            "3f00/7f21/6fb5": ("eMLPP", "Enhan Mult Lvl Prio"),
            "3f00/7f21/6fb6": ("AAeM", "Auto Answer for eMLPP"),
            "3f00/7f21/6fb7": ("ECC", "Emergency Call Codes"),
            "3f00/7f21/6fc5": ("PNN", "PLMN Network Name"),
            "3f00/7f21/6fc6": ("OPL", "Operator PLMN list"),
            "3f00/7f21/6fc7": ("MBDN", "Mailbox Dialling Nrs"),
            "3f00/7f21/6fc8": ("EXT6", "Extension6"),
            "3f00/7f21/6fc9": ("MBI", "Mailbox Identifier"),
            "3f00/7f21/6fca": ("MWIS", "Message Waiting Stat"),
            "3f00/7f21/6fcb": ("CFIS", "Call Fwd Ind Status"),
            "3f00/7f21/6fcc": ("EXT7", "Extension7"),
            "3f00/7f21/6fcd": ("SPDI", "Service Prov Display"),
            "3f00/7f21/6fce": ("MMSN", "MMS Notification"),
            "3f00/7f21/6fcf": ("EXT8", "Extension8"),
            "3f00/7f21/6fd0": ("MMSICP", "MMS Issuer Params"),
            "3f00/7f21/6fd1": ("MMSUP", "MMS User Preferences"),
            "3f00/7f21/6fd2": ("MMSUCP", "MMS User Params"),
            "3f00/7f21/6f06": ("USIMarr", "Access Rule Reference"),
            "3f00/7f21/6f08": ("USIMkeys", "Ciphering and keys"),
            "3f00/7f21/6f3b": ("USIMfdn", "Fixed numbers"),
            "3f00/7f21/6f3c": ("USIMsms", "SMS"),
            "3f00/7f21/6f40": ("USIMmsisdn", "MSISDN"),
            "3f00/7f21/6f42": ("USIMsmsp", "SMS parameters"),
            "3f00/7f21/6f43": ("USIMsmss", "SMS status"),
            "3f00/7f21/6f47": ("USIMsmsr", "SMS Status reports"),
            "3f00/7f21/6f49": ("USIMsdn", "Service Dialling Nrs"),
            "3f00/7f21/6f4a": ("USIMext1", "Extension 1"),
            "3f00/7f21/6f4b": ("USIMext2", "Extension 2"),
            "3f00/7f21/6f4c": ("USIMext3", "Extension 3"),
            "3f00/7f21/6f4d": ("USIMbdn", "Barred Numbers"),
            "3f00/7f21/6f4e": ("USIMext5", "Extension 5"),
            "3f00/7f21/6f4f": ("USIMccp2", "Capability Config 2"),
            "3f00/7f21/6f55": ("USIMext4", "Extension 4"),
            "3f00/7f21/6f56": ("USIMest", "Enabled Services"),
            "3f00/7f21/6f57": ("USIMacl", "Access Control List"),
            "3f00/7f21/6f58": ("USIMcmi", "Comparision Method"),
            "3f00/7f21/6f5b": ("USIMstarthfn", "Init for Hyperframe"),
            "3f00/7f21/6f5c": ("USIMthreshold", "Max value for START"),
            "3f00/7f21/6f73": ("USIMpsloci", "Packet switched locn"),
            "3f00/7f21/6f80": ("USIMici", "Incoming Calls"),
            "3f00/7f21/6f81": ("USIMoci", "Outgoing Calls"),
            "3f00/7f21/6f82": ("USIMict", "Incoming Call Timer"),
            "3f00/7f21/6f83": ("USIMoct", "Outgoing Call Timer"),
            "3f00/7f21/6fc3": ("USIMhiddenkey", "Key for hidden pbook"),
            "3f00/7f21/6fc4": ("USIMnetpar", "Network parameters"),
            "3f00/7f21/6fd3": ("USIMnia", "Network Ind Alerting"),
            "3f00/7f21/6fd4": ("USIMvgcsca", "Voice grp cipher alg"),
            "3f00/7f21/6fd5": ("USIMvbsca", "Voice brd cipher alg"),
            "3f00/7f21/6fd6": ("USIMgbabp", "GBA Bootstrap"),
            "3f00/7f21/6fd7": ("USIMmsk", "MBMS Service Keys"),
            "3f00/7f21/6fd8": ("USIMmuk", "MBMS User Key"),
            "3f00/7f21/6fd9": ("USIMehplmn", "Evuiv HPLMN"),
            "3f00/7f21/6fda": ("USIMgbanl", "GBA NAF List"),
            "3f00/7f21/5f3b": ("DFmultimedia", "Multi media Directory"),

            "3f00/7f22": ("IS-41", "IS-41 standard"),
            "3f00/7f23": ("FP-CTS", "Fixed Part Cordless Telephony System"),

            "3f00/7f45": ("S@T", "SIMalliance Toolbox"),
            "3f00/7f55": ("N@vigate", ""),
        }


class USIMCardFileMapping(SimCardFileMapping):
    def _get_files_details(self) -> dict:
        return {
            "7fff/6f05": ("LI", "Language indication"),
            "7fff/6f06": ("ARR", "Access Rule Reference"),
            "7fff/6f07": ("IMSI", "International Mobile Subscriber Identity"),
            "7fff/6f08": ("Keys", "Ciphering and Integrity Keys"),
            "7fff/6f09": ("KeysPS", "Ciphering and Integrity Keys for Packet Switched domain"),
            "7fff/6f2c": ("DCK", "Depersonalisation Control Keys"),
            "7fff/6f31": ("HPPLMN", "Higher Priority PLMN search period"),
            "7fff/6f32": ("CNL", "Co-operative Network List"),
            "7fff/6f37": ("ACMmax", "ACM maximum value"),
            "7fff/6f38": ("UST", "USIM Service Table"),
            "7fff/6f39": ("ACM", "Accumulated Call Meter"),
            "7fff/6f3b": ("FDN", "Fixed Dialling Numbers"),
            "7fff/6f3c": ("SMS", "Short messages"),
            "7fff/6f3e": ("GID1", "Group Identifier Level 1"),
            "7fff/6f3f": ("GID2", "Group Identifier Level 2"),
            "7fff/6f40": ("MSISDN", "MSISDN"),
            "7fff/6f41": ("PUCT", "Price per Unit and Currency Table"),
            "7fff/6f42": ("SMSP", "Short message service parameters"),
            "7fff/6f43": ("SMSS", "SMS status"),
            "7fff/6f45": ("CBMI", "Cell Broadcast Message identifier selection"),
            "7fff/6f46": ("SPN", "Service Provider Name"),
            "7fff/6f47": ("SMSR", "Short message status reports"),
            "7fff/6f48": ("CBMID", "Cell Broadcast Message Identifier for Data Download"),
            "7fff/6f49": ("SDN", "Service Dialling Numbers"),
            "7fff/6f4b": ("EXT2", "Extension2"),
            "7fff/6f4c": ("EXT3", "Extension3"),
            "7fff/6f4d": ("BDN", "Barred Dialling Numbers"),
            "7fff/6f4e": ("EXT5", "Extension5"),
            "7fff/6f4f": ("6f4f", "Capability Configuration Parameters 2"),
            "7fff/6f50": ("CBMIR", "Cell Broadcast Message Identifier Range selection"),
            "7fff/6f55": ("EXT4", "Extension4"),
            "7fff/6f56": ("EST", "Enabled Services Table"),
            "7fff/6f57": ("ACL", "Access Point Name Control List"),
            "7fff/6f58": ("CMI", "Comparison Method Information"),
            "7fff/6f5b": ("START-HFN", "Initialisation values for Hyperframe number"),
            "7fff/6f5c": ("THRESHOLD", "Maximum value of START"),
            "7fff/6f60": ("PLMNwAcT", "User controlled PLMN selector with Access Technology"),
            "7fff/6f61": ("OPLMNwACT", "Operator controlled PLMN selector with Access Technology"),
            "7fff/6f62": ("HPLMNwAcT", "HPLMN selector with Access Technology"),
            "7fff/6f73": ("PSLOCI", "Packet Switched location information"),
            "7fff/6f78": ("ACC", "Access Control Class"),
            "7fff/6f7b": ("FPLMN", "Forbidden PLMNs"),
            "7fff/6f7e": ("LOCI", "Location Information"),
            "7fff/6f80": ("ICI", "Incoming Call Information"),
            "7fff/6f81": ("OCI", "Outgoing Call Information"),
            "7fff/6f82": ("ICT", "Incoming Call Timer"),
            "7fff/6f83": ("OCT", "Outgoing Call Timer"),
            "7fff/6fad": ("AD", "Administrative Data"),
            "7fff/6fb1": ("VGCS", "Voice Group Call Service"),
            "7fff/6fb2": ("VGCSS", "Voice Group Call Service Status"),
            "7fff/6fb3": ("VBS", "Voice Broadcast Service"),
            "7fff/6fb4": ("VBSS", "Voice Broadcast Service Status"),
            "7fff/6fb5": ("eMLPP", "enhanced Multi Level Precedence and Pre-emption"),
            "7fff/6fb6": ("AaeM", "Automatic Answer for eMLPP Service"),
            "7fff/6fb7": ("ECC", "Emergency Call Codes"),
            "7fff/6fc3": ("Hiddenkey", "Key for hidden phone book entries"),
            "7fff/6fc4": ("NETPAR", "Network Parameters"),
            "7fff/6fc5": ("PNN", "PLMN Network Name"),
            "7fff/6fc6": ("OPL", "Operator PLMN List"),
            "7fff/6fc7": ("MBDN", "Mailbox Dialling Numbers"),
            "7fff/6fc8": ("EXT6", "Extension6"),
            "7fff/6fc9": ("MBI", "Mailbox Identifier"),
            "7fff/6fca": ("MWIS", "Message Waiting Indication Status"),
            "7fff/6fcb": ("CFIS", "Call Forwarding Indication Status"),
            "7fff/6fcc": ("EXT7", "Extension7"),
            "7fff/6fcd": ("SPDI", "Service Provider Display Information"),
            "7fff/6fce": ("MMSN", "MMS Notification"),
            "7fff/6fcf": ("EXT8", "Extension8"),
            "7fff/6fd0": ("MMSICP", "MMS Issuer Connectivity Parameters"),
            "7fff/6fd1": ("MMSUP", "MMS User Preferences"),
            "7fff/6fd2": ("MMSUCP", "MMS User Connectivity Parameters"),
            "7fff/6fd3": ("NIA", "Network's Indication of Alerting"),
            "7fff/6fd4": ("VGCSCA", "Voice Group Call Service Ciphering Algorithm"),
            "7fff/6fd5": ("VBSCA", "Voice Broadcast Service Ciphering Algorithm"),
            "7fff/6fd6": ("GBABP", "GBA Bootstrapping parameters"),
            "7fff/6fd7": ("MSK", "MBMS Service Keys List"),
            "7fff/6fd8": ("MUK", "MBMS User Key"),
            "7fff/6fd9": ("EHPLMN", "Equivalent HPLMN"),
            "7fff/6fda": ("GBANL", "GBA NAF List"),
            "7fff/6fdb": ("EHPLMNPI", "Equivalent HPLMN Presentation Indication"),
            "7fff/6fdc": ("LRPLMNSI", "Last RPLMN Selection Indication"),
            "7fff/6fdd": ("NAFKCA", "NAF Key Centre Address"),
            "7fff/6fde": ("SPNI", "Service Provider Name Icon"),
            "7fff/6fdf": ("PNNI", "PLMN Network Name Icon"),
            "7fff/6fe2": ("NCP-IP", "Network Connectivity Parameters for USIM IP connections"),
            "7fff/6fe3": ("EPSLOCI", "EPS location information"),
            "7fff/6fe4": ("EPSNSC", "EPS NAS Security Context"),
            "7fff/6fe6": ("UFC", "USAT Facility Control"),
            "7fff/6fe7": ("UICCIARI", "UICC IARI"),
            "7fff/6fe8": ("NASCONFIG", "Non Access Stratum Configuration"),
            "7fff/6fec": ("PWS", "Public Warning System"),
            "7fff/6fed": ("FDNURI", "Fixed Dialling Numbers URI"),
            "7fff/6fee": ("BDNURI", "Barred Dialling Numbers URI"),
            "7fff/6fef": ("SDNURI", "Service Dialling Numbers URI"),
            "7fff/6ff0": ("IWL", "IMEI(SV) White Lists"),
            "7fff/6ff1": ("IPS", "IMEI(SV) Pairing Status"),
            "7fff/6ff2": ("IPD", "IMEI(SV) of Pairing Device"),
            "7fff/6ff3": ("ePDGId", "Home ePDG Identifier"),
            "7fff/6ff4": ("ePDGSelection", "ePDG Selection Information"),
            "7fff/6ff5": ("ePDGIdEm", "Emergency ePDG Identifier"),
            "7fff/6ff6": ("ePDGSelectionEm", "ePDG Selection Information for Emergency Services"),
            "7fff/6ff7": ("FromPreferred", "From Preferred"),
            "7fff/6ff8": ("IMSConfigData", "IMS Configuration Data"),
            "7fff/6ff9": ("3GPPPSDATAOFF", "3GPP PS Data Off"),
            "7fff/6ffa": ("3GPPPSDATAOFFservicelist", "3GPP PS Data Off Service List"),
            "7fff/6ffb": ("TVCONFIG", "TV Configuration"),
            "7fff/6ffc": ("XCAPConfigData", "XCAP Configuration Data"),
            "7fff/6ffd": ("EARFCNList", "EARFCN list for MTC/NB-IOT UEs"),
            "7fff/6ffe": ("MuDMiDConfigData", "MuD and MiD configuration data"),

            "7fff/5f3a": ("DFphonebook", "Phone book Directory"),
            "7fff/5f3a/4f22": ("PSC", "Phone book Synchronisation Counter"),
            "7fff/5f3a/4f23": ("CC", "Change Counter"),
            "7fff/5f3a/4f24": ("PUID", "Previous Unique Identifier"),

            "7fff/5f3b": ("DFgsm-access", "GSM Access Directory"),
            "7fff/5f3b/4f20": ("Kc", "GSM Ciphering key Kc"),
            "7fff/5f3b/4f52": ("KcGPRS", "GPRS Ciphering key KcGPRS"),
            "7fff/5f3b/4f63": ("CPBCCH", "CPBCCH Information"),
            "7fff/5f3b/4f64": ("InvScan", "Investigation Scan"),

            "7fff/5f3c": ("DFmexe", "Mobile Execution Environment Directory"),
            "7fff/5f3c/4f40": ("MexE-ST", "MexE Service table"),
            "7fff/5f3c/4f41": ("ORPK", "Operator Root Public Key"),
            "7fff/5f3c/4f42": ("ARPK", "Administrator Root Public Key"),
            "7fff/5f3c/4f43": ("TPRPK", "Third Party Root Public Key"),

            "7fff/5f70": ("DFsolsa", "Support of Localised Service Area Directory"),
            "7fff/5f70/4f30": ("SAI", "SoLSA Access Indicator"),
            "7fff/5f70/4f31": ("SLL", "SoLSA LSA List"),

            "7fff/5f40": ("DFwlan", "WLAN Directory"),
            "7fff/5f40/4f41": ("Pseudo", "Pseudonym"),
            "7fff/5f40/4f42": ("UPLMNWLAN", "User controlled PLMN selector for I-WLAN Access"),
            "7fff/5f40/4f43": ("TPRPK", "Third Party Root Public Key"),
            "7fff/5f40/4f44": ("UWSIDL", "User controlled WLAN Specific Identifier List"),
            "7fff/5f40/4f45": ("OWSIDL", "Operator controlled WLAN Specific IdentifierList"),
            "7fff/5f40/4f46": ("WRI", "WLAN Reauthentication Identity"),
            "7fff/5f40/4f47": ("HWSIDL", "Home I-WLAN Specific Identifier List"),
            "7fff/5f40/4f48": ("WEHPLMNPI", "I-WLAN Equivalent HPLMN Presentation Indication"),
            "7fff/5f40/4f49": ("WHPI", "I-WLAN HPLMN Priority Indication"),
            "7fff/5f40/4f4a": ("WLRPLMN", "I-WLAN Last Registered PLMN"),
            "7fff/5f40/4f4b": ("HPLMNDAI", "HPLMN Direct Access Indicator"),

            "7fff/5f50": ("DFhnb", "Home NodeB Directory"),
            "7fff/5f50/4f81": ("ACSGL", "Allowed CSG Lists"),
            "7fff/5f50/4f82": ("CSGT", "CSG Type"),
            "7fff/5f50/4f83": ("HNBN", "Home NodeB Name"),
            "7fff/5f50/4f84": ("OCSGL", "Operator CSG Lists"),
            "7fff/5f50/4f85": ("OCSGT", "Operator CSG Type"),
            "7fff/5f50/4f86": ("OHNBN", "Operator Home NodeB Name"),

            "7fff/5f90": ("DFprose", "ProSe Directory"),
            "7fff/5f90/4f01": ("PROSE_MON", "ProSe Monitoring Parameters"),
            "7fff/5f90/4f02": ("PROSE_ANN", "ProSe Announcing Parameters"),
            "7fff/5f90/4f03": ("PROSEFUNC", "HPLMN ProSe Function"),
            "7fff/5f90/4f04": ("PROSE_RADIO_COM", "ProSe Direct Communication Radio Parameters"),
            "7fff/5f90/4f05": ("PROSE_RADIO_MON", "ProSe Direct Discovery Monitoring Radio Parameters"),
            "7fff/5f90/4f06": ("PROSE_RADIO_ANN", "ProSe Direct Discovery Announcing Radio Parameters"),
            "7fff/5f90/4f07": ("PROSE_POLICY", "ProSe Policy Parameters"),
            "7fff/5f90/4f08": ("PROSE_PLMN", "ProSe PLMN Parameters"),
            "7fff/5f90/4f09": ("PROSE_GC", "ProSe Group Counter"),
            "7fff/5f90/4f10": ("PST", "ProSe Service Table"),
            "7fff/5f90/4f11": ("PROSE_UIRC", "ProSe UsageInformationReportingConfiguration"),
            "7fff/5f90/4f12": ("PROSE_GM_DISCOVERY", "ProSe Group Member Discovery Parameters"),
            "7fff/5f90/4f13": ("PROSE_RELAY", "ProSe Relay Parameters"),
            "7fff/5f90/4f14": ("PROSE_RELAY_DISCOVERY", "ProSe Relay Discovery Parameters"),

            "7fff/5fa0": ("DFacdc", "ACDC Directory"),
            "7fff/5fa0/4f01": ("ACDC_LIST", "ACDC List"),

            "7fff/5fb0": ("DFtv", "TV Directory"),

            "7fff/5fc0": ("DF5gs", "5GS Directory"),
            "7fff/5fc0/4f01": ("5GS3GPPLOCI", "5GS 3GPP location information"),
            "7fff/5fc0/4f02": ("5GSN3GPPLOCI", "5GS non-3GPP location information"),
            "7fff/5fc0/4f03": ("5GS3GPPNSC", "5GS 3GPP Access NAS Security Context"),
            "7fff/5fc0/4f04": ("5GSN3GPPNSC", "5GS non-3GPP Access NAS Security Context"),
            "7fff/5fc0/4f05": ("5GAUTHKEYS", "5G authentication keys"),
            "7fff/5fc0/4f06": ("UAC_AIC", "UAC Access Identities Configuration"),
            "7fff/5fc0/4f07": ("SUCI_Calc_Info", "Subscription Concealed Identifier Calculation Information EF"),
            "7fff/5fc0/4f08": ("OPL5G", "5GS Operator PLMN List"),
            "7fff/5fc0/4f09": ("SUPI_NAI", "SUPI as Network Access Identifier"),
            "7fff/5fc0/4f0a": ("Routing_Indicator", "Routing Indicator"),
            "7fff/5fc0/4f0b": ("URSP", "UE Route Selection Policies"),
            "7fff/5fc0/4f0c": ("TN3GPPSNN", "Trusted non-3GPP Serving network names list"),
        }


class ISIMCardFileMapping(SimCardFileMapping):
    def _get_files_details(self) -> dict:
        return {
            "7fff/6f02": ("IMPI", "IMS private user identity"),
            "7fff/6f03": ("DOMAIN", "Home Network Domain Name"),
            "7fff/6f04": ("IMPU", "IMS public user identity"),
            "7fff/6f06": ("ARR", "Access Rule Reference"),
            "7fff/6f07": ("IST", "ISIM Service Table"),
            "7fff/6f09": ("P-CSCF", "P-CSCF Address"),
            "7fff/6f3c": ("SMS", "Short messages"),
            "7fff/6f42": ("SMSP", "Short message service parameters"),
            "7fff/6f43": ("SMSS", "SMS status"),
            "7fff/6f47": ("SMSR", "Short message status reports"),
            "7fff/6fad": ("AD", "Administrative Data"),
            "7fff/6fd5": ("GBABP", "GBA Bootstrapping parameters"),
            "7fff/6fd7": ("GBANL", "GBA NAF List"),
            "7fff/6fdd": ("NAFKCA", "NAF Key Centre Address"),
            "7fff/6fe7": ("UICCIARI", "UICC IARI"),
        }
